# Generated by Django 5.0.6 on 2024-05-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='fnacto',
            field=models.DateField(),
        ),
    ]
