# Generated by Django 5.0.6 on 2024-05-29 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_persona_correo_alter_persona_fnacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO'), ('O', 'OTRO')], max_length=1),
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=15)),
                ('edad', models.IntegerField(default=0)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.persona')),
            ],
        ),
    ]
