# Generated by Django 5.0.6 on 2024-05-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_persona_sexo_mascota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('REPTIL', 'Reptil'), ('OTRO', 'Otro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('F', 'FEMENINO'), ('O', 'OTRO'), ('M', 'MASCULINO')], max_length=1),
        ),
    ]
