# Generated by Django 5.0.6 on 2024-05-29 20:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_mascota_tipo_alter_persona_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='subtipo',
            field=models.CharField(choices=[('Otro', 'Otro'), ('Reptil', [('Lagarto', 'Lagarto'), ('Anaconda', 'Anaconda')]), ('PERRO', [('Chico', 'Chico'), ('Grande', 'Grande'), ('Verde', 'Verde')]), ('Gato', [('Volador', 'Volador'), ('Nian', 'Nian')])], default='Otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='edad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('PERRO', 'Perro'), ('REPTIL', 'Reptil'), ('OTRO', 'Otro'), ('GATO', 'Gato')], max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO'), ('O', 'OTRO')], max_length=1),
        ),
    ]
