# Generated by Django 5.0.6 on 2024-06-21 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_persona_foto_alter_mascota_subtipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='subtipo',
            field=models.CharField(choices=[('Otro', 'Otro'), ('Gato', [('Volador', 'Volador'), ('Nian', 'Nian')]), ('Reptil', [('Lagarto', 'Lagarto'), ('Anaconda', 'Anaconda')]), ('PERRO', [('Chico', 'Chico'), ('Grande', 'Grande'), ('Verde', 'Verde')])], default='Otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('OTRO', 'Otro'), ('REPTIL', 'Reptil')], max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO'), ('O', 'OTRO')], max_length=1),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=9, null=True)),
                ('direccion', models.CharField(max_length=500)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
