# Generated by Django 5.0.6 on 2024-06-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_persona_foto_alter_mascota_subtipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='subtipo',
            field=models.CharField(choices=[('Otro', 'Otro'), ('PERRO', [('Chico', 'Chico'), ('Grande', 'Grande'), ('Verde', 'Verde')]), ('Reptil', [('Lagarto', 'Lagarto'), ('Anaconda', 'Anaconda')]), ('Gato', [('Volador', 'Volador'), ('Nian', 'Nian')])], default='Otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('REPTIL', 'Reptil'), ('GATO', 'Gato'), ('OTRO', 'Otro'), ('PERRO', 'Perro')], max_length=15),
        ),
        migrations.AlterField(
            model_name='persona',
            name='sexo',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('O', 'OTRO'), ('F', 'FEMENINO')], max_length=1),
        ),
    ]
